# Generated by Django 5.0.6 on 2024-09-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_livro_categoria_livro_editora"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name": "Autor", "verbose_name_plural": "Autores"},
        ),
        migrations.AlterModelOptions(
            name="categoria",
            options={"verbose_name": "Categoria", "verbose_name_plural": "Categorias"},
        ),
        migrations.AlterModelOptions(
            name="editora",
            options={"verbose_name": "Editora", "verbose_name_plural": "Editoras"},
        ),
        migrations.AlterModelOptions(
            name="livro",
            options={"verbose_name": "Livro", "verbose_name_plural": "Livros"},
        ),
        migrations.RenameField(
            model_name="livro",
            old_name="título",
            new_name="titulo",
        ),
    ]
