# Generated by Django 5.1.1 on 2024-10-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_itenscompra"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livro",
            old_name="autores",
            new_name="autor",
        ),
    ]
