# Generated by Django 5.1.1 on 2024-12-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_itenscompra_preco"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livro",
            old_name="autor",
            new_name="autores",
        ),
    ]
